In [134]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

In [92]:
try:
    raw_engine = create_engine("mysql+mysqlconnector://root:NiCk!4355@127.0.0.1/health_claimsdb")

    df_2008 = pd.read_sql("SELECT * FROM beneficiarysummarysample_2008 LIMIT 20", raw_engine)

    print("Connection successful and data retrieved:")
    display(df_2008)

except Exception as e:

    print(f"An error occured: {e}")

Connection successful and data retrieved:

,beneficiary_id,birth_date,death_date,gender_code,race_code,esrd_indicator,state_code,county_code,medicare_coverage_months,supplementary_coverage_months,...,stroke,medical_reimbursement_inpatient,beneficiary_responsibility_inpatient,payment_inpatient,medical_reimbursement_outpatient,beneficiary_responsibility_outpatient,payment_outpatient,medical_reimbursement_carrier,beneficiary_responsibility_carrier,payment_carrier
0,00013D2EFD8E45D1,19230501,,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0
1,00016F745862898F,19430101,,1,1,0,39,230,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0
2,0001FDD721E223DC,19360901,,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,,1,5,0,06,290,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,30.0,40.0,0.0,220.0,80.0,0.0
5,0002DAE1C81CC70D,19431001,,1,2,0,33,400,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0002F28CE057345B,19220701,,1,1,0,39,270,12,12,...,2,0.0,0.0,0.0,1010.0,270.0,0.0,3330.0,940.0,0.0
7,000308435E3E5B76,19350901,,1,1,0,24,680,10,10,...,2,0.0,0.0,0.0,150.0,160.0,0.0,870.0,340.0,80.0
8,000345A39D4157C9,19760901,,2,1,0,23,810,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,00036A21B65B0206,19381001,,2,2,0,01,570,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,000489E7EAAD463F,19340201,,2,1,0,15,140,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,1980.0,420.0,0.0
11,00048EF1F4791C68,19290601,,1,1,0,44,230,11,11,...,2,0.0,0.0,0.0,50.0,30.0,0.0,400.0,250.0,30.0
12,0004F0ABD505251D,19360701,,2,1,0,41,30,12,12,...,2,0.0,0.0,0.0,4580.0,560.0,0.0,3760.0,1350.0,0.0
13,00052705243EA128,19340501,,1,1,0,14,982,12,12,...,2,14000.0,1024.0,0.0,4240.0,3130.0,0.0,6740.0,2130.0,1200.0
14,00070B63745BE497,19360301,,2,1,0,13,270,12,12,...,2,0.0,0.0,0.0,100.0,20.0,0.0,930.0,220.0,0.0
15,0007E57CC13CE880,19340101,,1,1,0,06,140,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0007F12A492FD25D,19190901,,2,2,0,34,400,12,12,...,1,5000.0,1024.0,0.0,5510.0,1380.0,0.0,4980.0,1170.0,200.0
17,000A005BA0BED3EA,19191001,,2,2,0,50,160,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,000B97BA2314E971,19380401,,1,1,0,22,20,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,1020.0,290.0,0.0
19,000C7486B11E7030,19320801,,1,2,0,25,350,12,12,...,2,30000.0,1024.0,0.0,0.0,0.0,0.0,720.0,290.0,0.0

In [101]:
mapping = {
    'DESYNPUF_ID': 'beneficiary_id',
    'BENE_BIRTH_DT': 'birth_date',
    'BENE_DEATH_DT': 'death_date',
    'BENE_SEX_IDENT_CD': 'gender_code',
    'BENE_RACE_CD': 'race_code',
    'SP_STATE_CODE': 'state_code',
    'BENE_COUNTY_CD': 'county_code',

    'SP_ALZHDMTA': 'alzheimers_disease',
    'SP_CHF': 'congestive_heart_failure',
    'SP_CHRNKIDN': 'chronic_kidney_disease',
    'SP_CNCR': 'cancer',
    'SP_COPD': 'copd',
    'SP_DEPRESSN': 'depression',
    'SP_DIABETES': 'diabetes',
    'SP_ISCHMCHT': 'ischemic_heart_disease',
    'SP_OSTEOPRS': 'osteoporosis',
    'SP_RA_OA': 'rheumatoid_arthritis_oa',
    'SP_STRKETIA': 'stroke',

    'PPPYMT_IP': 'payment_inpatient',
    'PPPYMT_OP': 'payment_outpatient',
    'PPPYMT_CAR': 'payment_carrier',
    'MEDREIMB_IP': 'medical_reimbursement_inpatient',
    'BENRES_IP': 'beneficiary_responsibility_inpatient',
    'MEDREIMB_OP': 'medical_reimbursement_outpatient',
    'BENRES_OP': 'beneficiary_responsibility_outpatient',
    'MEDREIMB_CAR': 'medical_reimbursement_carrier',
    'BENRES_CAR': 'beneficiary_responsibility_carrier',

    'BENE_ESRD_IND': 'esrd_indicator',
    'BENE_HI_CVRAGE_TOT_MONS': 'medicare_coverage_months',
    'BENE_SMI_CVRAGE_TOT_MONS': 'supplementary_coverage_months',
    'BENE_HMO_CVRAGE_TOT_MONS': 'hmo_coverage_months',
    'PLAN_CVRG_MOS_NUM': 'plan_coverage_months'
}

df_2008.rename(columns=mapping, inplace=True)

df_2008.head()

,beneficiary_id,birth_date,death_date,gender_code,race_code,esrd_indicator,state_code,county_code,medicare_coverage_months,supplementary_coverage_months,...,stroke,medical_reimbursement_inpatient,beneficiary_responsibility_inpatient,payment_inpatient,medical_reimbursement_outpatient,beneficiary_responsibility_outpatient,payment_outpatient,medical_reimbursement_carrier,beneficiary_responsibility_carrier,payment_carrier
0,00013D2EFD8E45D1,19230501,,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0
1,00016F745862898F,19430101,,1,1,0,39,230,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0
2,0001FDD721E223DC,19360901,,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,,1,5,0,06,290,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,30.0,40.0,0.0,220.0,80.0,0.0

Data Cleaning (Preprocessing)

In [102]:
df_2008

,beneficiary_id,birth_date,death_date,gender_code,race_code,esrd_indicator,state_code,county_code,medicare_coverage_months,supplementary_coverage_months,...,stroke,medical_reimbursement_inpatient,beneficiary_responsibility_inpatient,payment_inpatient,medical_reimbursement_outpatient,beneficiary_responsibility_outpatient,payment_outpatient,medical_reimbursement_carrier,beneficiary_responsibility_carrier,payment_carrier
0,00013D2EFD8E45D1,19230501,,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0
1,00016F745862898F,19430101,,1,1,0,39,230,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0
2,0001FDD721E223DC,19360901,,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,,1,5,0,06,290,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,30.0,40.0,0.0,220.0,80.0,0.0
5,0002DAE1C81CC70D,19431001,,1,2,0,33,400,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0002F28CE057345B,19220701,,1,1,0,39,270,12,12,...,2,0.0,0.0,0.0,1010.0,270.0,0.0,3330.0,940.0,0.0
7,000308435E3E5B76,19350901,,1,1,0,24,680,10,10,...,2,0.0,0.0,0.0,150.0,160.0,0.0,870.0,340.0,80.0
8,000345A39D4157C9,19760901,,2,1,0,23,810,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,00036A21B65B0206,19381001,,2,2,0,01,570,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,000489E7EAAD463F,19340201,,2,1,0,15,140,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,1980.0,420.0,0.0
11,00048EF1F4791C68,19290601,,1,1,0,44,230,11,11,...,2,0.0,0.0,0.0,50.0,30.0,0.0,400.0,250.0,30.0
12,0004F0ABD505251D,19360701,,2,1,0,41,30,12,12,...,2,0.0,0.0,0.0,4580.0,560.0,0.0,3760.0,1350.0,0.0
13,00052705243EA128,19340501,,1,1,0,14,982,12,12,...,2,14000.0,1024.0,0.0,4240.0,3130.0,0.0,6740.0,2130.0,1200.0
14,00070B63745BE497,19360301,,2,1,0,13,270,12,12,...,2,0.0,0.0,0.0,100.0,20.0,0.0,930.0,220.0,0.0
15,0007E57CC13CE880,19340101,,1,1,0,06,140,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0007F12A492FD25D,19190901,,2,2,0,34,400,12,12,...,1,5000.0,1024.0,0.0,5510.0,1380.0,0.0,4980.0,1170.0,200.0
17,000A005BA0BED3EA,19191001,,2,2,0,50,160,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,000B97BA2314E971,19380401,,1,1,0,22,20,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,1020.0,290.0,0.0
19,000C7486B11E7030,19320801,,1,2,0,25,350,12,12,...,2,30000.0,1024.0,0.0,0.0,0.0,0.0,720.0,290.0,0.0

In [103]:
df_2008.columns

Index(['beneficiary_id', 'birth_date', 'death_date', 'gender_code',
       'race_code', 'esrd_indicator', 'state_code', 'county_code',
       'medicare_coverage_months', 'supplementary_coverage_months',
       'hmo_coverage_months', 'plan_coverage_months', 'alzheimers_disease',
       'congestive_heart_failure', 'chronic_kidney_disease', 'cancer', 'copd',
       'depression', 'diabetes', 'ischemic_heart_disease', 'osteoporosis',
       'rheumatoid_arthritis_oa', 'stroke', 'medical_reimbursement_inpatient',
       'beneficiary_responsibility_inpatient', 'payment_inpatient',
       'medical_reimbursement_outpatient',
       'beneficiary_responsibility_outpatient', 'payment_outpatient',
       'medical_reimbursement_carrier', 'beneficiary_responsibility_carrier',
       'payment_carrier'],
      dtype='str')

In [126]:
df_2008.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 34 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   beneficiary_id                         20 non-null     str
 1   birth_date                             20 non-null     int64
 2   death_date                             20 non-null     str
 3   gender_code                            20 non-null     int64
 4   race_code                              20 non-null     int64
 5   esrd_indicator                         20 non-null     int64
 6   state_code                             20 non-null     str
 7   county_code                            20 non-null     int64
 8   medicare_coverage_months               20 non-null     int64
 9   supplementary_coverage_months          20 non-null     int64
 10  hmo_coverage_months                    20 non-null     int64
 11  plan_coverage_months                   20 non-null     str
 12  alzheimers_disease                     20 non-null     int64
 13  congestive_heart_failure               20 non-null     int64
 14  chronic_kidney_disease                 20 non-null     int64
 15  cancer                                 20 non-null     int64
 16  copd                                   20 non-null     int64
 17  depression                             20 non-null     int64
 18  diabetes                               20 non-null     int64
 19  ischemic_heart_disease                 20 non-null     int64
 20  osteoporosis                           20 non-null     int64
 21  rheumatoid_arthritis_oa                20 non-null     int64
 22  stroke                                 20 non-null     int64
 23  medical_reimbursement_inpatient        20 non-null     float64
 24  beneficiary_responsibility_inpatient   20 non-null     float64
 25  payment_inpatient                      20 non-null     float64
 26  medical_reimbursement_outpatient       20 non-null     float64
 27  beneficiary_responsibility_outpatient  20 non-null     float64
 28  payment_outpatient                     20 non-null     float64
 29  medical_reimbursement_carrier          20 non-null     float64
 30  beneficiary_responsibility_carrier     20 non-null     float64
 31  payment_carrier                        20 non-null     float64
 32  deceased                               20 non-null     int64
 33  age                                    20 non-null     int64
dtypes: float64(9), int64(21), str(4)
memory usage: 5.4 KB

Replace numeric values 1 (for yes) and 2 (for no) with binary 1 and 0 respectively for the chronic condition columns. This will make it easier to analyze the presence or absence of these conditions.

In [111]:
df_2008['alzheimers_disease'] = df_2008['alzheimers_disease'].replace(2, 0)
df_2008['diabetes'] = df_2008['diabetes'].replace(2, 0)
df_2008['congestive_heart_failure'] = df_2008['congestive_heart_failure'].replace(2, 0)
df_2008['chronic_kidney_disease'] = df_2008['chronic_kidney_disease'].replace(2, 0)
df_2008['cancer'] = df_2008['cancer'].replace(2, 0)
df_2008['copd'] = df_2008['copd'].replace(2, 0)
df_2008['depression'] = df_2008['depression'].replace(2, 0)
df_2008['ischemic_heart_disease'] = df_2008['ischemic_heart_disease'].replace(2, 0)
df_2008['osteoporosis'] = df_2008['osteoporosis'].replace(2, 0)
df_2008['rheumatoid_arthritis_oa'] = df_2008['rheumatoid_arthritis_oa'].replace(2, 0)
df_2008['stroke'] = df_2008['stroke'].replace(2, 0)

Create a boolean column named 'deceased' that serves as a flag, derived from the presence of a value in the 'death_date' column.

In [114]:
df_2008['deceased'] = df_2008['death_date'].notnull().astype(int)

Create a new column that shows the age of people

In [119]:
df_2008['age'] = 2008 - pd.to_numeric(df_2008['birth_date'].astype(str).str[:4])

Return the number of missing values per column

In [145]:
df_2008 = df_2008.replace('', np.nan)
df_2008 = df_2008.replace(r'^\s*$', np.nan, regex=True)

In [146]:
print(df_2008.isnull().sum())

beneficiary_id                            0
birth_date                                0
death_date                               20
gender_code                               0
race_code                                 0
esrd_indicator                            0
state_code                                0
county_code                               0
medicare_coverage_months                  0
supplementary_coverage_months             0
hmo_coverage_months                       0
plan_coverage_months                      0
alzheimers_disease                        0
congestive_heart_failure                  0
chronic_kidney_disease                    0
cancer                                    0
copd                                      0
depression                                0
diabetes                                  0
ischemic_heart_disease                    0
osteoporosis                              0
rheumatoid_arthritis_oa                   0
stroke                                    0
medical_reimbursement_inpatient           0
beneficiary_responsibility_inpatient      0
payment_inpatient                         0
medical_reimbursement_outpatient          0
beneficiary_responsibility_outpatient     0
payment_outpatient                        0
medical_reimbursement_carrier             0
beneficiary_responsibility_carrier        0
payment_carrier                           0
deceased                                  0
age                                       0
dtype: int64

Statistical Summary and Visualizing Outliers

In [149]:
df_2008.describe() # Computes count, mean, std deviation, min/max and quartiles for numerical columns.

,birth_date,gender_code,race_code,esrd_indicator,county_code,medicare_coverage_months,supplementary_coverage_months,hmo_coverage_months,alzheimers_disease,congestive_heart_failure,...,beneficiary_responsibility_inpatient,payment_inpatient,medical_reimbursement_outpatient,beneficiary_responsibility_outpatient,payment_outpatient,medical_reimbursement_carrier,beneficiary_responsibility_carrier,payment_carrier,deceased,age
count,2.000000e+01,20.000000,20.000000,20.0,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.00000,20.0,20.00000,20.000000,20.0,20.000000,20.000000,20.000000,20.0,20.000000
mean,1.935265e+07,1.400000,1.450000,0.0,389.600000,10.050000,10.050000,2.800000,0.100000,0.150000,...,153.60000,0.0,786.00000,280.000000,0.0,1282.500000,386.000000,75.500000,1.0,72.800000
std,1.200763e+05,0.502625,0.944513,0.0,285.183302,4.358597,4.358597,5.042973,0.307794,0.366348,...,375.13989,0.0,1747.42939,745.103313,0.0,1924.328659,574.322484,268.846953,0.0,12.007015
min,1.919090e+07,1.000000,1.000000,0.0,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,32.000000
25%,1.931325e+07,1.000000,1.000000,0.0,212.500000,11.750000,11.750000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,70.000000
50%,1.935560e+07,1.000000,1.000000,0.0,285.000000,12.000000,12.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.00000,0.000000,0.0,550.000000,230.000000,0.000000,1.0,72.500000
75%,1.938055e+07,2.000000,2.000000,0.0,575.000000,12.000000,12.000000,2.000000,0.000000,0.000000,...,0.00000,0.0,112.50000,70.000000,0.0,1260.000000,360.000000,0.000000,1.0,76.750000
max,1.976090e+07,2.000000,5.000000,0.0,982.000000,12.000000,12.000000,12.000000,1.000000,1.000000,...,1024.00000,0.0,5510.00000,3130.000000,0.0,6740.000000,2130.000000,1200.000000,1.0,89.000000